### ISSUE TITLE
Option to avoid auto-connecting

### ISSUE THREAD

**Issue by erik-stephens** [terascope/terafoundation_kafka_connector#15]
The new kafka slicer will want to `client.on('ready', ...)` in order to read topic metadata.  It's possible for this event to be fired by the time it's able to setup the event handler.  Should we add an `autoconnect (default=true)` option or require callers to query metadata?  There may be other event handlers (eg `event.error`, `event.log`) that could benefit from no auto-connecting.

**Comment by kstaken** [comment]
This was resolved in #16
