### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by peterdemartini** [terascope/terafoundation_kafka_connector#21]
This project should be published to NPM under `terafoundation-kafka-connector`. Additionally, this should be done in an automated fashion.

**Comment by kstaken** [comment]
FYI: Changing the name of this project will break the way it is loaded in terafoundation.

**Comment by peterdemartini** [comment]
I am aware, that is why I broke these out into individual issues because some of them are more complicated than the others.

**Comment by peterdemartini** [comment]
I added an issue to terafoundation for this particular change. https://github.com/terascope/terafoundation/issues/112

**Comment by peterdemartini** [comment]
This project moved to [kafka-assets](https://github.com/terascope/kafka-assets)
