### ISSUE TITLE
Update to support Kafka v0.11.0 

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/terafoundation_kafka_connector#9]
Update the terafoundation_kafka_connector to support Kafka v0.11.0.0.
Error occurs when using current version of connector with Kafka 2.11-0.11.0.0.  Calling producer.produce() does not throw an error, but hangs at flush until it errors out.

Error Message:
```
[15:46] 
An error has occurred: Error: Local: Timed out
        at Error (native), message:  { slice_id: ‘82c32a81-0a2f-455a-85c7-3c4db5f50cc1’,
      request: 200,
      slicer_id: 0,
      slicer_order: 7 }
```

**Comment by kstaken** [comment]
This is no longer an issue.
